DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS movies;

CREATE TABLE users
(
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    nickname            VARCHAR(50) NOT NULL,
    email               VARCHAR(100) NOT NULL UNIQUE,
    password_hash       CHAR(64) NOT NULL,
    profile_picture_url VARCHAR(255) DEFAULT 'https://i.pinimg.com/474x/9e/83/75/9e837528f01cf3f42119c5aeeed1b336.jpg?nii=t' NOT NULL,
    date_of_birth       DATE NOT NULL,
    date_of_joining     DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    bio                 TEXT
);

CREATE TABLE movies
(
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    title        VARCHAR(255) NOT NULL,
    description  TEXT NOT NULL,
    genre        VARCHAR(100) NOT NULL,
    director     VARCHAR(100) NOT NULL,
    release_date DATE NOT NULL,
    runtime      INT NOT NULL,
    poster_url   VARCHAR(500) NOT NULL,
    youtube_html_url  VARCHAR(500) NOT NULL
);

CREATE TABLE ratings
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id    INT NOT NULL,
    movie_id   INT NOT NULL,
    score      DECIMAL(3, 1) NOT NULL CHECK (score >= 1.0 AND score <= 10.0),
    comment    TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    edited BOOL DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE,
    UNIQUE (user_id, movie_id)
);


INSERT INTO users (nickname, email, password_hash, profile_picture_url, date_of_birth, date_of_joining, bio)
VALUES
    ('ADMIN','king@example.com','0b14d501a594442a01c6859541bcb3e8164d183d32937b851835442f69d5c94e','https://cdn.pfps.gg/pfps/9319-lego-star-wars-31.png', '1992-05-12', '2023-06-12', 'Film buff since the 90s. Grew up on Spielberg and Lucas, now exploring world cinema. I believe every movie deserves at least one watch, but not every movie deserves a second. Admin of "Forgotten Classics" Facebook group.'),
    ('coffeeandframes','sarah.j@example.com', '6cf615d5bcaac778352a8f1f3360d23f02f34ec182e259897fd6ce485d7870d4',  'https://pics.craiyon.com/2023-10-27/51bd27e80c554b11af16a1660230a762.webp', '1998-11-23', '2024-10-03', 'MA in Film Studies from NYU. Working on my PhD thesis about feminist theory in neo-noir. Letterboxd addict. My blood type is espresso. She/her.'),
    ('RedLetterReviewer', 'critical.mark@example.com',  '5906ac361a137e2d286465cd6588ebb5ac3f5ae955001100bc41577c3d751764', 'https://cdn.pfps.gg/pfps/9038-funny-star-wars.png', '1985-03-30', '2020-01-20','Former film critic for a local newspaper before print media died. Now just yelling into the void online. I love cinema, but I hate what Marvel did to it. Letterboxd pro member since 2015.'),
    ('kenobiiiaaahahah', 'jessica.k@example.com','b97873a40f73abedd8d685a7cd5e5f85e4a9cfb83eac26886640a0813850122b','https://preview.redd.it/monke-image-dump-19-v0-lgarrkehrnsa1.jpg?width=1280&format=pjpg&auto=webp&s=9369c4fee3f03b9ad7a36ed6b73e1b70c1649b9f','2003-07-15', '2025-09-23', 'im here for fun movies!! not into artsy stuff. Star Wars prequels > originals (fight me). I just wanna turn my brain off and enjoy the ride!! 🍿🎬'),
    ('n3on_dream5','neo.w@example.com','c2a6b1f0b8e34d4b4f2a6cdb38fbe2c5fbbdce51fa0d0a2e6c6c0c1cce3a1e21','https://tse4.mm.bing.net/th/id/OIP.YqRl-HUQCHEbvXOqC8SUugHaEK?rs=1&pid=ImgDetMain&o=7&rm=3','1995-02-01','2022-04-18','Vaporwave aesthetic enthusiast. Obsessed with synth scores and neon-soaked cinematography. Refn, Villeneuve, and Nicolas Winding are my holy trinity. Currently building a home theater with RGB everything.'),
    ('ContemplativeCinephile','slow.cinema@example.com','9a1f4c0b2f84a1f8b0a56f0a6c77a5e3a5c8c1b74c4b5d8f1bfa6a9a2e7d1a0c','https://th.bing.com/th/id/R.3b585281e1bacc2c8d0e87d7aaa7afde?rik=sVQFdDKm4FfWOg&pid=ImgRaw&r=0','1989-09-09','2021-11-02','Tarr, Angelopoulos, Tarkovsky. If it has a 10-minute static shot, I am already interested. Patient cinema for patient viewers. Life moves fast enough—movies should not.'),
    ('24fps_perfectionist','fbf.editor@example.com','4d91f1c6c8a7e2b93d0f56a9b2c4f8e1c9b5f6d3a1e2c4b6d8e9f0a1b2c3','https://tse3.mm.bing.net/th/id/OIP.QcLdFHdoI2JA3MN7FCAvRwHaFB?rs=1&pid=ImgDetMain&o=7&rm=3','1993-06-17','2023-08-29','Professional video editor for 8 years. I notice every bad cut, every continuity error, every color grade mistake. It is both a blessing and a curse. Thelma Schoonmaker is my hero.'),
    ('WatchedItTwice','genres@example.com','1f8c9a6b7d2e3c4b5a9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0','https://i.ytimg.com/vi/wNnu2IYCcrw/maxresdefault.jpg','2000-12-04','2024-01-11','Genre completionist. Horror Monday, Western Tuesday, Noir Wednesday... you get the idea. 2,847 films logged. My watchlist is longer than my life expectancy.'),
    ('CelluloidPurist','analog.rules@example.com','7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f','https://i.redd.it/mvqb290ypfs31.jpg','1982-04-22','2019-05-07','35mm or nothing. Digital projection killed the soul of cinema. I drive 2 hours to watch films on actual film stock. My local arthouse theater knows me by name.'),
    ('MidnightMovieMadness','lnv@example.com','e1f2d3c4b5a697887766554433221100ffeeddccbbaa998877665544332211','https://tse4.mm.bing.net/th/id/OIP.7HzEuOnuzqeAyzvNfPJ07wHaHa?rs=1&pid=ImgDetMain&o=7&rm=3','1997-10-31','2022-12-19','Insomniac cinephile. Something about watching movies at 2 AM hits different. The silence, the darkness, just you and the screen. Horror and noir are best consumed in the witching hour.'),
    ('RottenTomatoKiller','tomaytoe@example.com','5ed728c2fa5d767bc6c1ec6a732db1e37c343be46913e6498d340f7782691f14','https://tse3.mm.bing.net/th/id/OIP.RhcqsqEGS3B3NfnjP3ktJgHaHa?rs=1&pid=ImgDetMain&o=7&rm=3','1967-10-06','2020-01-05','Retired high school English teacher. Been watching movies since before the New Hollywood era. I have seen trends come and go. Modern blockbusters lack soul.');

INSERT INTO movies (title, description, genre, director, release_date, runtime, poster_url, youtube_html_url)
VALUES
    ('Inception', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', 'sci-fi', 'Christopher Nolan', '2010-07-16', 148, 'https://image.tmdb.org/t/p/original/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg', 'https://www.youtube.com/embed/YoHD9XEInc0'),
    ('The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'drama', 'Frank Darabont', '1994-09-22', 142, 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', 'https://www.youtube.com/embed/PLl99DlL6b4'),
    ('The Godfather', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'crime', 'Francis Ford Coppola', '1972-03-24', 175, 'https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'https://www.youtube.com/embed/UaVTIH8mujA'),
    ('Pulp Fiction', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'crime', 'Quentin Tarantino', '1994-10-14', 154, 'https://image.tmdb.org/t/p/original/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', 'https://www.youtube.com/embed/s7EdQ4FqbhY'),
    ('The Dark Knight', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'action', 'Christopher Nolan', '2008-07-18', 152, 'https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'https://www.youtube.com/embed/EXeTwQWrcwY'),
    ('Forrest Gump', 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold from the perspective of an Alabama man with an IQ of 75.', 'drama', 'Robert Zemeckis', '1994-07-06', 142, 'https://image.tmdb.org/t/p/original/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', 'https://www.youtube.com/embed/bLvqoHBptjg'),
    ('Fight Club', 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', 'drama', 'David Fincher', '1999-10-15', 139, 'https://image.tmdb.org/t/p/original/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', 'https://www.youtube.com/embed/qtRKdVHc-cE'),
    ('The Matrix', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 'sci-fi', 'Lana Wachowski, Lilly Wachowski', '1999-03-31', 136, 'https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', 'https://www.youtube.com/embed/vKQi3bBA1y8'),
    ('Interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 'sci-fi', 'Christopher Nolan', '2014-11-07', 169, 'https://tse2.mm.bing.net/th/id/OIP.uiaj_IMaC7h3NoieAhcmVwHaLG?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'https://www.youtube.com/embed/zSWdZVtXT7E'),
    ('Parasite', 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 'thriller', 'Bong Joon Ho', '2019-05-30', 132, 'https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'https://www.youtube.com/embed/5xH0HfJHsaY'),
    ('Blade Runner 2049','Young Blade Runner K''s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.','sci-fi','Denis Villeneuve','2017-10-06',164,'https://image.tmdb.org/t/p/original/aMpyrCizvSdc0UIMblJ1srVgAEF.jpg','https://www.youtube.com/embed/gCcx85zbxz4'),
    ('No Country for Old Men','Violence and chaos follow when a hunter stumbles upon a drug deal gone wrong and takes the cash.','thriller','Joel Coen, Ethan Coen','2007-11-21',122,'https://image.tmdb.org/t/p/original/6d5XOczc226jECq0LIX0siKtgHR.jpg','https://www.youtube.com/embed/38A__WT3-o0'),
    ('Whiplash','A promising young drummer enrolls at a cut-throat music conservatory.','drama','Damien Chazelle','2014-10-10',107,'https://media.port.hu/images/000/714/141.jpg','https://www.youtube.com/embed/7d_jQycdQGo'),
    ('Her','In the near future, a lonely writer develops an unlikely relationship with an operating system.','romance','Spike Jonze','2013-12-18',126,'https://image.tmdb.org/t/p/original/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg','https://www.youtube.com/embed/WzV6mXIOVl4'),
    ('There Will Be Blood','A story of family, religion, hatred, oil and madness.','drama','Paul Thomas Anderson','2007-12-26',158,'https://m.media-amazon.com/images/I/712hOZ1UCmL.jpg','https://www.youtube.com/embed/FeSLPELpMeM'),
    ('Arrival','A linguist works with the military to communicate with alien lifeforms.','sci-fi','Denis Villeneuve','2016-11-11',116,'https://image.tmdb.org/t/p/original/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg','https://www.youtube.com/embed/tFMo3UJ4B4g'),
    ('Oldboy','After being kidnapped and imprisoned for years, a man seeks revenge.','thriller','Park Chan-wook','2003-11-21',120,'https://www.themoviedb.org/t/p/original/idBaREsAGTjPZPrlAd1w8SVzUzd.jpg','https://www.youtube.com/embed/2HkjrJ6IK5E');

INSERT INTO ratings (user_id, movie_id, score, comment)
VALUES
    (1, 1, 10, 'Nolan crafted something truly special here. After watching Inception for the fifth time, I still catch new details in every viewing. The practical effects in the hallway scene remain mind-blowing even after all these years - no CGI could replicate that visceral feeling of reality bending. The way Nolan plays with time, dreams, and architecture creates this intricate puzzle that rewards repeat viewings. Zimmer''s score is absolutely legendary, especially "Time" which has become one of the most recognizable pieces of film music in the 21st century. The ensemble cast delivers phenomenal performances, with Tom Hardy and Marion Cotillard being particular standouts. DiCaprio brings real emotional weight to Cobb''s guilt and obsession. This is what blockbuster cinema should aspire to be - intelligent, ambitious, and thoroughly entertaining. A defining film of its decade.'),
    (1, 8, 9, 'Game changer. The CGI aged a bit but the philosophy remains timeless.'),
    (1, 9, 7, 'Visually it is absolutely gorgeous, Hoyte van Hoytema''s cinematography deserves every award it got. But Nolan''s obsession with making everything so complex ended up hurting the emotional core of the story. The bookshelf scene in the fifth dimension felt more like a gimmick than genuine emotional catharsis. Matthew McConaughey tries his best to sell it, but even his charisma cannot save some of those clunky exposition-heavy dialogues. The first act on Earth is fantastic, the space exploration parts are incredible, but once we get to the tesseract sequence I felt the movie trying too hard to be profound. Still worth watching for the spectacle alone.'),

    (2, 2, 10, 'This film has made me cry at least seven times across different viewings. The relationship between Andy and Red is one of the most beautifully portrayed friendships in cinema history. What strikes me most about Shawshank is its unwavering faith in human dignity and hope, even in the darkest circumstances. Freeman''s narration guides us through decades with warmth and wisdom, while Robbins plays Andy with this quiet determination that makes the final act so cathartic. The cinematography by Roger Deakins is stunning - those shots of the prison yard, the library, the final beach scene in Zihuatanejo. Thomas Newman''s score swells at just the right moments. This is a film about patience, resilience, and the unbreakable human spirit. Absolutely perfect.'),
    (2, 6, 8, 'Hanks at his peak. A lovely journey through American history.'),
    (2, 4, 7, 'Tarantino''s dialogue is incredible as always - the Ezekiel 25:17 speech, the Royale with Cheese conversation, the uncomfortable tension of the Brett interrogation. Where Pulp Fiction loses me is in its excessive violence that sometimes feels gratuitous rather than purposeful. The Gimp scene, Marvin getting shot in the face - these moments feel like Tarantino showing off rather than serving the story. Still, the nonlinear structure is masterfully executed and the performances across the board are fantastic. Samuel L. Jackson deserved that Oscar.'),

    (3, 5, 6, 'Here is my controversial take: The Dark Knight is a great Joker movie trapped inside a mediocre Batman film. Ledger''s performance is transcendent, yes, but it completely overshadows everything else. The Two-Face arc feels rushed and tacked on, like they crammed two movies into one. The action sequences are shot competently but lack visual flair - that tunnel chase is decent but nothing special. Christian Bale''s growling Batman voice has aged terribly and is almost comical now. The film asks interesting questions about chaos versus order, but does not trust the audience enough to explore them subtly. Nolan hits you over the head with his themes. Without Ledger, this would be remembered as just another superhero movie. With him, it is elevated to something more, but the surrounding film does not quite match his level.'),
    (3, 10, 9, 'Finally, something fresh from a master filmmaker. Bong Joon-ho weaves social commentary into every frame without ever feeling preachy. The production design is impeccable - the contrast between the cramped semi-basement and the modernist mansion tells you everything about class division before a single word of dialogue. What impressed me most is how the tone shifts seamlessly from comedy to thriller to tragedy. The peach scene, the birthday party, the flood - each sequence ratchets up the tension while maintaining that pitch-black humor. This is what happens when you give a visionary director complete creative control. Korean cinema has been showing Hollywood how it is done for years now.'),
    (3, 7, 5, 'Fight Club thinks it is way smarter than it actually is. Yes, we get it - consumerism bad, masculinity in crisis, society makes us feel empty. The twist is predictable if you have watched any psychological thriller before. Norton and Pitt have great chemistry, but Helena Bonham Carter''s character feels like a male fantasy rather than an actual person. Fincher''s direction is stylish but the style overwhelms any substance. The biggest problem? The film attracts exactly the kind of toxic dudebro fans it is supposedly criticizing. That alone tells you the satire failed. It is basically American Psycho for people who think they are deep. Maybe I am just too old to find this edgy philosophy profound anymore.'),

    (4, 1, 7, 'ok so like... i didnt understand everything that was happening lol. dreams within dreams within dreams? my brain hurt trying to follow it all haha. BUT it looked really cool!! that hallway fight scene was INSANE. Leo is always great and i love Marion Cotillard. the ending with the spinning top was a nice touch, left me thinking about it after. would probably need to watch it again to fully get it but idk if i have the attention span for that 😅'),
    (4, 5, 10, 'BEST. SUPERHERO. MOVIE. EVER. MADE. Heath Ledger IS the Joker, nobody will ever top this performance EVER. The hospital explosion scene?? ICONIC. "Why so serious?" lives rent free in my head. Christian Bale is amazing as Batman and the whole cast is just *chefs kiss*. Some people complain its too long or too serious but those people are WRONG. This movie proved superhero films can be art. RIP Heath Ledger, gone way too soon but your legacy lives forever in this masterpiece 🦇🃏'),
    (4, 3, 3, 'i tried watching this bc everyone says its a classic but omg SO BORING. literally nothing happens for like the first hour, just people talking in dark rooms. i fell asleep twice and when i woke up they were still just talking!! wheres the action?? i thought this was supposed to be about the mafia but its just old men having meetings. also its wayyyy too long, like nearly 3 hours?? no movie needs to be that long. idk maybe im just not cultured enough to appreciate it but i was bored out of my mind 🥱'),

    (5, 11, 10, 'Villeneuve achieved something remarkable - a sequel that not only honors the original but expands its universe in meaningful ways. The original Blade Runner asked what it means to be human; 2049 asks what it means to have a soul when your entire existence might be a fabrication. Gosling plays K with this beautiful melancholy, a replicant longing for something more. The reveal that he is NOT the chosen one subverts expectations perfectly. Deakins'' cinematography is hypnotic - every frame is a painting. That orange wasteland, the purple-hazed Las Vegas, the rain-soaked neon streets. The synth score by Zimmer and Wallfisch pays homage to Vangelis while creating its own identity. This is mature, patient sci-fi that trusts its audience. A crushing meditation on purpose and meaning.'),
    (6, 15, 8, 'This film stressed me out in the best possible way. Chazelle''s editing creates this relentless rhythm that mirrors the jazz drumming at its center. Every cut feels like a whip crack. J.K. Simmons is absolutely terrifying as Fletcher - not through physical violence primarily, but through psychological manipulation and the systematic destruction of a young man''s self-worth. The question the film asks is disturbing: does greatness require abuse? Can we separate the art from the suffering that created it? I do not think the film answers these questions definitively, which is what makes it so compelling. Teller''s transformation from eager student to obsessed perfectionist is harrowing to watch.'),
    (7, 16, 7, 'Arrival has a beautiful concept - using linguistics as a tool for understanding consciousness and time perception. The twist regarding Louise''s "memories" is elegant and emotionally resonant. Amy Adams delivers a performance of quiet intelligence and growing sorrow. Where the film stumbles is in its execution of the military/government subplot, which feels underdeveloped and relies too heavily on clichés about warmongering generals. The Chinese General plot resolution via phone call feels contrived. Still, Villeneuve''s direction is assured and Bradford Young''s cinematography creates an appropriately alien atmosphere. The film works best when focused on language and loss.'),
    (8, 12, 9, 'The Coen Brothers stripped away all sentimentality to create pure, cold dread. No Country for Old Men is a masterclass in tension - that hotel shootout scene with the silencer, the cat-and-mouse chase, the coin toss philosophy. Javier Bardem''s Anton Chigurh is one of the most terrifying villains in cinema, not because he is evil in a traditional sense, but because he operates on a logic completely foreign to human emotion. He is fate personified, death as an unstoppable force. The decision to have no score amplifies every sound - footsteps, breathing, the wind. Roger Deakins makes the Texas landscape feel vast and indifferent to human suffering. Bleakly beautiful.'),
    (9, 14, 7, 'Her captures something real about loneliness and connection in the digital age, even if the premise is far-fetched. Phoenix is incredible as always, conveying so much with just his face and voice. Scarlett Johansson''s vocal performance as Samantha is surprisingly layered and nuanced. The production design creates this near-future LA that feels both familiar and slightly off - high-waisted pants and pastel colors everywhere. What bothers me is the film''s gender politics feel a bit undercooked. Samantha is essentially a manic pixie dream AI, designed to be the perfect woman without the messiness of actual human needs. Still, as a meditation on disconnection it resonates.'),
    (10, 13, 10, 'Daniel Day-Lewis delivers what might be the single greatest acting performance I have ever witnessed on film. His Daniel Plainview is a monster wrapped in American ambition, greed incarnate with an oil derrick for a heart. The way he commands every scene, that voice, those silences - it is mesmerizing and horrifying. Paul Dano holds his own as the equally manipulative Eli Sunday, representing religion as Plainview represents capitalism, two parasites feeding off desperate people. PTA''s direction is operatic in scope, Jonny Greenwood''s discordant strings create unbearable tension. That final scene in the bowling alley is both tragic and darkly comic. This is American mythology stripped to its brutal core.'),
    (5, 17, 8, 'Oldboy is a revenge thriller that goes places most films would not dare. Park Chan-wook''s direction is stylish without being flashy - that hammer fight sequence done in one take is iconic for a reason. The twist at the end is genuinely disturbing and reframes everything that came before. Choi Min-sik''s performance captures a man absolutely destroyed by circumstances beyond his comprehension, then rebuilt into a weapon. The hypnosis ending is both merciful and tragic. Korean cinema''s willingness to explore dark psychology without Hollywood''s need for redemption makes this unforgettable.'),

    (5, 8, 9, 'Still holds up. Bullet-time is iconic.'),
    (6, 11, 7, 'Gorgeous but sloooow. Villeneuve needs a better editor.'),
    (7, 4, 6, 'Nonlinear structure feels gimmicky on rewatches. Tarantino showing off.'),
    (8, 15, 9, 'J.K. Simmons is terrifying. That final scene *chefs kiss*.'),
    (9, 2, 8, 'Beautiful film about hope. Drags a bit in the middle but the ending makes it worthwhile.'),
    (10, 12, 8, 'Brutal minimalism. The Coens at their coldest.'),
    (11, 16, 9, 'Emotionally devastating. The final reveal recontextualizes everything in the most heartbreaking way possible.'),
    (5, 6, 7, 'Forrest Gump is technically impressive - the visual effects seamlessly integrate Hanks into historical footage, and the makeup ages him convincingly across decades. But here is my problem: the film''s ideology is deeply conservative. It rewards Forrest for being simple and obedient while punishing Jenny for exercising agency and exploring countercultural movements. The message seems to be "do not question authority, do not think too hard, just run." The 60s and 70s are reduced to a greatest hits compilation without engaging with the actual social upheaval. Hanks is charming enough to make you overlook this, but I cannot shake the feeling that I am being sold a sanitized, feel-good version of American history.'),
    (6, 17, 10, 'Technically perfect. Deeply disturbing. Cannot unsee it.'),
    (7, 5, 8, 'Ledger elevates it. Without him, it is just solid.'),
    (11, 1, 4, 'I know this is unpopular, but Inception is the perfect example of Nolan''s worst tendencies as a filmmaker. It is so concerned with explaining its own mechanics that it forgets to make us care about the characters. We get endless exposition dumps about dream levels and kicks and totems, but virtually no character development. Cobb''s dead wife motivation is one-dimensional. The heist crew are all archetypes without inner lives. The film is cold and clinical when it should be surreal and emotional. Dreams should feel dreamlike, but Nolan shoots them like corporate espionage sequences. Everything is grey and concrete and literal. For a movie about dreams, it has shockingly little imagination. The spinning top ending does not make up for two and a half hours of joyless puzzle-solving. Nolan is a great technician but a mediocre storyteller.'),
    (11, 9, 5, 'Interstellar is beautiful space imagery wrapped around pseudoscientific nonsense and emotional manipulation. The first act shows promise - the dying Earth, the desperate mission. But once we hit the water planet and learn about time dilation, the plot becomes increasingly absurd. Black hole surfing? A fifth-dimensional bookcase? Love as a quantifiable force transcending space-time? Give me a break. Nolan wants to make 2001: A Space Odyssey but lacks Kubrick''s restraint and ambiguity. Instead, he over-explains everything while simultaneously making no sense. McConaughey watching his kids age via video messages is emotional manipulation at its most cynical. Hans Zimmer''s organ score drowns out half the dialogue. The ending is nonsense dressed up as profundity. Gravity did space better. Arrival did time better. This is Nolan at his most self-indulgent.'),
    (4, 9, 9, 'space is so pretty!! the wormhole scene was AMAZING i literally gasped. and the part where he watches his kids grow up while he is in space made me CRY 😭😭 yeah i didnt really understand the science stuff about black holes and dimensions but who cares, it FELT real and thats what matters!! McConaughey is perfect. also TARS the robot is hilarious, i want one as a pet lol. some people say its too long but i was glued to the screen the whole time!!'),
    (2, 1, 8, 'Inception remains Nolan''s most tightly constructed narrative puzzle. What I appreciate from an academic standpoint is how the film uses architecture as metaphor for consciousness - Ariadne literally designs minds, spaces become memories, physics reflects psychology. The layered structure mirrors psychoanalytic theory about the unconscious. My only criticism is that for a film about dreams, it lacks true surrealism. Everything is too logical, too controlled. Real dreams have an illogic that Nolan avoids in favor of heist movie mechanics. Still, as a blend of blockbuster entertainment and intellectual ambition, it succeeds admirably.');


